// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrWW8JMOKcJp87aRMBIfMGpmciqAIDAU',
    appId: '1:24617827560:web:29d4053f6cc01272d71d5d',
    messagingSenderId: '24617827560',
    projectId: 'smartbudget-88efb',
    authDomain: 'smartbudget-88efb.firebaseapp.com',
    storageBucket: 'smartbudget-88efb.firebasestorage.app',
    measurementId: 'G-V1KHYYYBTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsQDkk3ljTXSk2nu8K5U5KVR9kfgW8eM',
    appId: '1:24617827560:android:db90c9832d2ab7a5d71d5d',
    messagingSenderId: '24617827560',
    projectId: 'smartbudget-88efb',
    storageBucket: 'smartbudget-88efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUsSq6TY14mS6XJfHu_G0Ig2gb-enYrs',
    appId: '1:24617827560:ios:76b071b029f68577d71d5d',
    messagingSenderId: '24617827560',
    projectId: 'smartbudget-88efb',
    storageBucket: 'smartbudget-88efb.firebasestorage.app',
    iosBundleId: 'com.example.proyectoApp',
  );
}
